### ISSUE TITLE
[Lithium-v0.6.4-b2] Incompatiblity with Performant.

### ISSUE THREAD

**Issue by Cixon** [AeiouEnigma/lithium-forge#1]
### Builds
FORGE v36.1.4
Lithium build 2 v0.6.4

### Reproduction Steps
1. Install [Performant](https://www.curseforge.com/minecraft/mc-mods/performant).
2. Launch Minecraft.
3. See crash report.

### Crash Report File
[crash-2021-05-07_23.41.09-client.txt](https://github.com/AeiouEnigma/lithium-forge/files/6448442/crash-2021-05-07_23.41.09-client.txt)

### Context
Performant works just fine without Lithium installed however, once lithium is installed, it crashes on start up.

**Comment by Cixon** [comment]
**P.S:** Excellent work on porting Lithium to forge. I appreciate your dedication and effort to this project!

**Comment by AeiouEnigma** [comment]
As I understand it, Performant does a lot of unsafe (for compatibility) things, so I'm not optimistic about being able to resolve incompatibility with it. But I'll at least see if I can find some combination of Lithium mixins to disable if Performant is detected.

Thanks for documenting this :)

**Comment by Cixon** [comment]
> 
I'll at least see if I can find some combination of Lithium mixins to disable if Performant is detected.
> 

This would be a great solution! I wouldn't mind using Lithium instead of Performant for now. They both are similar mods but I do prefer lithium. Thank you for speedy reply! :)

**Comment by AeiouEnigma** [comment]
The issue seems to be confined to mixin.gen.features and mixin.world.block_entity_ticking. Worlds load up fine with Performant installed and those mixins disabled. I'll have an update out tonight or tomorrow that automatically disables those mixins when Performant is installed. Ideally we'd have a more proper fix than that, but I can't actually look at Performant's source code to determine if that makes sense, so this will have to do.

**Comment by Cixon** [comment]
> 
> 
> The issue seems to be confined to mixin.gen.features and mixin.world.block_entity_ticking. Worlds load up fine with Performant installed and those mixins disabled. I'll have an update out tonight or tomorrow that automatically disables those mixins when Performant is installed. Ideally we'd have a more proper fix than that, but I can't actually look at Performant's source code to determine if that makes sense, so this will have to do.

This seems like a pretty safe move. I will say I have talked to the performant creator before and he/she is pretty talkative and friendly. Whenever you find the time I'm sure if you were to request information from them they should provide it so perhaps in the future, both mods can complement each other nicely.

Thank you again!

**Comment by Cixon** [comment]
Woo! Glad to see progress but I just tested this on my client and my minecraft test server bench and this issue still occurs. They both crash when using Lithium amd Performant.

My forge version is 36.1.4

**Comment by Cixon** [comment]
Client crashes while the server simply doesn't launch. I hope to see this addressed soon! Thank you again!

**Comment by AeiouEnigma** [comment]
Could you please share your crash log? I can't diagnose the problem without that, unless you mean it's the exact same crash that you posted above

**Comment by AeiouEnigma** [comment]
If you mean you're still getting that same client crash, that baffles me because I haven't been able to reproduce that crash using just performant and lithium

**Comment by AeiouEnigma** [comment]
If you could share the latest.log from the client and the server, that might have helpful information too

**Comment by Cixon** [comment]
> If you could share the latest.log from the client and the server, that might have helpful information too

I will attempt this. Last time I checked it didn't get a crash report.

**Comment by Cixon** [comment]
Here's the server latest.log:
[latest.log](https://github.com/AeiouEnigma/lithium-forge/files/6469704/latest.log)

Here's the client latest.log:
[latest.log](https://github.com/AeiouEnigma/lithium-forge/files/6469700/latest.log)

**Comment by Cixon** [comment]
I was using performant v3.56m and b3 of lithium forge. Not sure if this makes a difference but my forge version is 36.1.4.

Perhaps the b3 jar u uploaded was a red herring by accident and I don't have the performant compat after all? Not sure but I do know one thing, I don't recieve crash reports from either the client or the test server so I certainly have a different lithium jar than the last one. 

The older one, b2 provided a crashlog.

**Comment by AeiouEnigma** [comment]
Looks like I may have missed some mixin conflicts. I'll put out a new build shortly.

**Comment by Cixon** [comment]
> 
> 
> Looks like I may have missed some mixin conflicts. I'll put out a new build shortly.

Excellent! Sorry for any inconvenience. I appreciate your speedy reply!

**Comment by AeiouEnigma** [comment]
Please don't apologize! Having mod conflicts documented here helps everyone :)

**Comment by AeiouEnigma** [comment]
...Honestly, I wonder if it even makes sense to try to resolve these conflicts. Lithium and Performant have essentially the same goal of improving server tick rates. The main difference is that Lithium aims to do so without changing functionality.

By the time I'd be done disabling all of the Lithium mixins that conflict with Performant, you'd essentially be just running Performant alongside a hollowed-out husk of Lithium.

Is your server tick rate with Lithium alone unsatisfactory?

**Comment by Cixon** [comment]
> 
> 
> ...Honestly, I wonder if it even makes sense to try to resolve these conflicts. Lithium and Performant have essentially the same goal of improving server tick rates. The main difference is that Lithium aims to do so without changing functionality.
> 
> By the time I'd be done disabling all of the Lithium mixins that conflict with Performant, you'd essentially be just running Performant alongside a hollowed-out husk of Lithium.
> 
> Is your server tick rate with Lithium alone unsatisfactory?

Well, no. I just figured running performant alongside lithium would wager some sort of EXTRA benefit. Despite both mods being so similar, I didn't know that Lithium would be _'hollowed-out'_ by the end of your testing.

Though, performant does do its job, the lithium project is moderately better in comparison. I guess this means performant is incompatible with Lithium?

**Comment by AeiouEnigma** [comment]
Actually it may not have ended up being quite that large of a list of conflicts. I just uploaded a hotfix build under the "Build 3" release numbered build_3a. Please see if it fixes the issue for you.

**Comment by Cixon** [comment]
**This issue is resolved!** May I ask, what features are disabled if performant is detected and what features remain?

**Comment by AeiouEnigma** [comment]
The following features are disabled when Performant is installed:

Optimized tracking of nearby entities for AI purposes
Village point of interest scanning
Entity collision checking
Optimized entity data tracking
Ticking of BlockEntities/TileEntities
World ticking optimizations

So far, the overwhelming majority of Lithium functionality remains enabled when Performant is installed, though this could change if more crashes come up during actual gameplay with Lithium and Performant installed.

These are the mixin rules that are disabled when Performant is installed: {"ai.nearby_entity_tracking.goals", "ai.poi.fast_retrieval", "collections.entity_filtering", "entity.collisions", "entity.data_tracker.use_arrays", "gen.features", "world.block_entity_ticking", "world.chunk_tickets", "world.chunk_ticking", "world.player_chunk_tick"}

You can read about what these mean, and which Lithium optimizations remain enabled, here: https://github.com/CaffeineMC/lithium-fabric/wiki/Configuration-File
