### ISSUE TITLE
Sudden crash on SP world while exploring caves, may be linked to When Dungeons Arrive and Omni mod

### ISSUE THREAD

**Issue by BugmanBugman** [AeiouEnigma/lithium-forge#2]
### Reproduction Steps
So far i'm not sure how to reproduce it, but I noticed exploring the world with omni and WDA mods tends to soft lock the server. This could be related

The crash log I linked names Lithium as a cause
### Crash Report File
[crash-2021-05-20_13.08.38-server.txt](https://github.com/AeiouEnigma/lithium-forge/files/6517990/crash-2021-05-20_13.08.38-server.txt)

**Comment by AeiouEnigma** [comment]
Would you mind going into your /config/fabrication/features.ini file, and setting `cracking_spawn_eggs=false` ?

It's just a theory, but I think that Fabrication/Forgery may have a mixin that doesn't like Omni passing a null parameter to a particular method call.

**Comment by AeiouEnigma** [comment]
Closing this issue, as it's a Fabrication issue and I've submitted a fix for it.
