### ISSUE TITLE
Crash with Quark

### ISSUE THREAD

**Issue by Ramwa803** [AeiouEnigma/lithium-forge#6]
1. Loading Quark r2.4-312, autoreglib-1.6-49 and lithium forge 0.6.3-1 with forge 36.1.0 (Minecraft 1.16.5)
2. The game crashes during mojang loading screen without a crash report

lithium and autoreglib load without problems
quark and autoreglib load without problems

**Comment by AeiouEnigma** [comment]
I'm unable to reproduce this using Quark r2.4-314 and AutoRegLib 1.6-49. Would you mind sharing a latest.log for when this happens?

**Comment by Ramwa803** [comment]
Using the latest versions of quark, autoreglib, lithium forge and forge, it seems that it was fixed. Now I and can enter the game and join a world normally :o
